[workspace]
resolver = "2"
members = ["crates/ably-chat-rs", "crates/ably-chat-rs-openapi"]

[workspace.package]
version = "0.1.0"
authors = ["Andrii Radyk <andrii@natter.co>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.85"
# TODO: set before publish
# repository = "https://github.com/<you>/ably-chat-rs"
