[workspace]
resolver = "3"
members = ["crates/ably-chat-rs", "crates/ably-chat-openapi", "crates/ably-auth-openapi"]

[workspace.package]
version = "0.2.0"
authors = ["Andrii Radyk <andrii@natter.co>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/AnderEnder/ably-chat-rs"
homepage = "https://github.com/AnderEnder/ably-chat-rs"
